import os

WEB_EXPERIMENT_ENABLED = os.getenv("WEB_EXPERIMENT", "0") == "1"

CLOB_HOST = os.getenv("WEB_EXPERIMENT_CLOB_HOST", "https://clob.polymarket.com")
CHAIN_ID = int(os.getenv("WEB_EXPERIMENT_CHAIN_ID", "137"))

SESSION_COOKIE_NAME = "opipolix_webexp_session"
SESSION_TTL_SECONDS = int(os.getenv("WEB_EXPERIMENT_SESSION_TTL_SECONDS", "43200"))
NONCE_TTL_SECONDS = int(os.getenv("WEB_EXPERIMENT_NONCE_TTL_SECONDS", "300"))

AUTH_RATE_LIMIT_WINDOW_SECONDS = int(
    os.getenv("WEB_EXPERIMENT_AUTH_RATE_WINDOW_SECONDS", "60")
)
AUTH_RATE_LIMIT_MAX_REQUESTS = int(
    os.getenv("WEB_EXPERIMENT_AUTH_RATE_MAX_REQUESTS", "30")
)

TP_POLL_SECONDS = float(os.getenv("WEB_EXPERIMENT_TP_POLL_SECONDS", "2"))
TP_MAX_MINUTES = int(os.getenv("WEB_EXPERIMENT_TP_MAX_MINUTES", "30"))

CLOB_AUTH_DOMAIN_NAME = "ClobAuthDomain"
CLOB_AUTH_DOMAIN_VERSION = "1"
CLOB_AUTH_MESSAGE = "This message attests that I control the given wallet"

DEFAULT_EXCHANGE_ADDRESS = "0x4bFb41d5B3570DeFd03C39a9A4D8dE6Bd8B8982E"

_FORCE_SIGNATURE_TYPE_RAW = os.getenv("WEB_EXPERIMENT_FORCE_SIGNATURE_TYPE", "").strip()
FORCE_SIGNATURE_TYPE = (
    int(_FORCE_SIGNATURE_TYPE_RAW)
    if _FORCE_SIGNATURE_TYPE_RAW in {"0", "1", "2"}
    else None
)

_FORCE_TRADING_ADDRESS_RAW = os.getenv("WEB_EXPERIMENT_FORCE_TRADING_ADDRESS", "").strip()
FORCE_TRADING_ADDRESS = _FORCE_TRADING_ADDRESS_RAW or None
